app_id: 835d7bbd-85bb-4c73-97f8-ce0740f151a7
publisher_name: YuanDevLLC
publisher_url: https://github.com/OneXray/OneXray
display_name: OneXray
script_template: inno_setup.iss
create_desktop_icon: true
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
